security_github_client_id: some_security_github_client_id
security_github_client_secret: some_security_github_client_secret
security_github_organizations: "some_security_github_organization:some_team"
