---
environments:
  default:
    values:
      - ../../values/global.yaml.gotmpl
      - ../../values/_version.yaml
      #{{- if isFile "/helm-values/security.yaml" }}
      - /helm-values/security.yaml
      #{{- else }}
      - ../../values/.security.test.yaml
      #{{- end }}
      - values/_kustomize.yaml.gotmpl
      - values/default.yaml.gotmpl
---
helmDefaults:
  wait: true
  timeout: 600
  recreatePods: true
  force: false
---
repositories:
  #{{- range $key, $value := .Values.helm_chart_repository }}
  - name: "{{ $key }}"
    url: "{{ $value }}"
  #{{- end }}
