# Common values shared for all charts
release_name: datahub-local-core

ingress_hostname: homelab.alvsanand.com
ingress_port: 443

namespaces:
  - data
  - monitoring
  - other

traeffik:
  auth_enabled: true

  middleware:
    monitoring-alertmanager:
      stripPrefixPath: /monitoring/alertmanager
      namespace: monitoring
    data-minio:
      stripPrefixPath: /data/minio
      namespace: data

helm_chart_version:
  homepage: "1.2.3"
  kube_prometheus_stack: "58.7.2"
  minio: "5.2.0"
