# Common values shared for all charts
release_name: datahub-local-core

ingress_hostname: homelab.alvsanand.com
ingress_port: 443

namespaces:
  - monitoring
  - other

traeffik:
  auth_enabled: true

  middleware:
    monitoring-alertmanager:
      stripPrefixPath: monitoring/alertmanager
      namespace: monitoring
