---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "kubeconfigCreatorName" .}}
  
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
data:
  create-kubeconfig.sh: | {{- .Files.Get "files/scripts/create-kubeconfig.sh" | nindent 4 }}