{{- range $secretName, $value := .Values.sealed_secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ $secretName }}"
  namespace: "{{ $value.namespace }}"
spec:
  encryptedData:
  {{- range $key, $encryptedData := $value.data }}
    {{ $key }}: "{{ $encryptedData }}"
  {{- end }}
  template:
    metadata:
      creationTimestamp: null
      name: "{{ $secretName }}"
      namespace: "{{ $value.namespace }}"
{{- end }}