{{- range $secretName, $value := .Values.sealed_secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ $secretName }}"
  namespace: "{{ $value.namespace }}"
spec:
  encryptedData:
  {{- range $key, $encryptedData := $value.data }}
    {{ $key }}: "{{ $encryptedData }}"
  {{- end }}
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      name: "{{ $secretName }}"
      namespace: "{{ $value.namespace }}"
{{- end }}