{
 "title": "Homelab / Homepage",
 "tags": [
  "Homelab",
  "Homepage"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "k8s_version",
    "query": {
     "query": "label_values(kube_node_info, kubelet_version)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Kubernetes Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "<div class=\"text-center\">\n  <img style=\"height:80px\" src=\"https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_without_workmark.svg\">\n  <h2 style=\"padding-top:15px\">$k8s_version</h2>\n</div>"
   }
  },
  {
   "title": "Cluster CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))*100"
    }
   ]
  },
  {
   "title": "Cluster Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Longhorn Cluster Storage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (longhorn_node_storage_usage_bytes) / sum (longhorn_node_storage_capacity_bytes-longhorn_node_storage_reservation_bytes)",
     "legendFormat": "Reserved"
    },
    {
     "expr": "sum (longhorn_disk_usage_bytes) / sum (longhorn_disk_capacity_bytes)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "UPS Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge"
    }
   ]
  },
  {
   "title": "Healthy Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_spec_unschedulable==0)"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_spec_unschedulable!=0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores)" }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sum(machine_memory_bytes)" }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (longhorn_volume_actual_size_bytes)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (longhorn_node_storage_capacity_bytes)"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": " * OL - On line (mains is present)\n * OB - On battery (mains is not present)\n * LB - Low battery\n * HB - High battery\n * RB - The battery needs to be replaced\n * CHRG - The battery is charging\n * DISCHRG - The battery is discharging (inverter is providing load power)\n * BYPASS - UPS bypass circuit is active -- no battery protection is available\n * CAL - UPS is currently performing runtime calibration (on battery)\n * OFF - UPS is offline and is not supplying power to the load\n * OVER - UPS is overloaded\n * TRIM - UPS is trimming incoming voltage (called \"buck\" in some hardware)\n * BOOST - UPS is boosting incoming voltage\n * FSD and SD - Forced Shutdown",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status == 1",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime"
    }
   ]
  },
  {
   "title": "Cluster Nodes Uptime",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((time() - node_boot_time_seconds{job=\"node-exporter\"}) / 86400)\n  * on(instance) group_left(nodename)\n    node_uname_info{job=\"node-exporter\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Cluster CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "avg(avg_over_time(node_hwmon_temp_celsius[1m])) by (instance) * on(instance) group_left(nodename) node_uname_info{job=\"node-exporter\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Cluster HDD Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "avg(avg_over_time(smartmon_temperature_celcius[1m])) by (instance) * on(instance) group_left(nodename) node_uname_info{job=\"node-exporter\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 12, "w": 5, "x": 0, "y": 17 } },
  {
   "title": "Alerts",
   "type": "table",
   "description": "Table containing the list of Alerts",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 17 },
   "targets": [
    {
     "expr": "(\n  label_replace(ALERTS_FOR_STATE{severity=~\"critical|warning|error|info\"}, \"instance_ip\", \"$1\", \"instance\", \"([^:]+)(:[0-9]+)?$\")\n  * on(instance_ip) group_left(nodename)\n  max by(instance_ip, nodename) (\n    label_replace(node_uname_info{job=\"node-exporter\"}, \"instance_ip\", \"$1\", \"instance\", \"([^:]+)(:[0-9]+)?$\")\n  )\n)\nor\n(\n  label_replace(ALERTS_FOR_STATE{severity=~\"critical|warning|error|info\"}, \"instance_ip\", \"$1\", \"instance\", \"([^:]+)(:[0-9]+)?$\")\n  unless on(instance_ip)\n  max by(instance_ip) (\n    label_replace(node_uname_info{job=\"node-exporter\"}, \"instance_ip\", \"$1\", \"instance\", \"([^:]+)(:[0-9]+)?$\")\n  )\n)"
    }
   ]
  }
 ]
}