{
 "title": "Homelab / Monitoring / Troubleshooting",
 "description": "Troubleshooting Dashboard for kubernetes",
 "tags": [
  "Homelab",
  "System",
  "Troubleshooting",
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_created,node)"
    }
   },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "search", "label": "String Match" },
   {
    "name": "duration",
    "label": "duration",
    "query": "5m,10m,30m,1h,2h,6h,12h,1d,2d,5d,14d,30d"
   },
   {
    "name": "container_error",
    "label": "Container error",
    "query": {
     "query": "query_result(kube_pod_container_status_waiting_reason{namespace=\"$namespace\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace $namespace details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)" }
   ]
  },
  {
   "title": "Cluster Age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - kube_service_created{namespace=~\"default\",service=\"kubernetes\"})"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{namespace=~\"$namespace\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVCs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{job=\"kube-state-metrics\",phase=\"Failed\",namespace=~\"$namespace\"} != 0) "
    }
   ]
  },
  {
   "title": "PVCs Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{job=\"kube-state-metrics\",phase=\"Pending\",namespace=~\"$namespace\"} != 0)"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_created{namespace=~\"$namespace\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_statefulset_created{namespace=~\"$namespace\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Total  pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~\"$namespace\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Ready pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{namespace=~\"$namespace\",node=~\"$node\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods/container",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{namespace=~\"$namespace\",node=~\"$node\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated{namespace=~\"$namespace\",node=~\"$node\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_daemonset_created{namespace=~\"$namespace\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_ingress_created{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "ConfigMaps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_configmap_created{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_secret_created{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PODs running in $namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=~\"$namespace\"}"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}"
    },
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", node=~\"$node\"}"
    },
    {
     "expr": "time() - kube_pod_start_time{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "PODs with errors in $namespace",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=~\"$namespace\"}"
    },
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", node=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVCs available capacity in namespacee $namespace",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=~\"$namespace\"}\n  / kubelet_volume_stats_capacity_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=~\"$namespace\"}\n ",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PersistentVolumeClaim status in namespace $namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(kube_persistentvolumeclaim_access_mode{namespace=~\"$namespace\"})",
     "legendFormat": "{{access_mode}}::{{persistentvolumeclaim}}"
    },
    {
     "expr": "kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\",phase=\"Bound\"}",
     "legendFormat": "Bound::{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Ingress in $namespace namespace",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_ingress_path{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Last 100  error logs from  container: $container_error",
   "type": "logs",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{stream=\"stderr\", namespace=~\"$namespace\", pod=~\"$container_error\"}  |= \"$search\" | logfmt",
     "maxLines": 100
    }
   ]
  }
 ]
}