{
 "title": "Homelab / Monitoring / Alerts",
 "description": "Updated dashboard for Alertamanager",
 "tags": [
  "Homelab",
  "Monitoring",
  "AlertManager"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(alertmanager_build_info,pod)"
    }
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {
     "query": "query_result(ALERTS_FOR_STATE{severity=~\"critical|warning|error|info\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of active alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{state=\"active\", pod=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "description": "Table containing the list of Alerts",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "ALERTS_FOR_STATE{severity=~\"$severity\"}"
    }
   ]
  },
  {
   "title": "Number of suppressed alerts",
   "type": "stat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{state=\"suppressed\", pod=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of active silences",
   "type": "stat",
   "description": "Current number of active silences.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(alertmanager_silences{state=\"active\", pod=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notifications sent from $instance",
     "type": "timeseries",
     "description": "Number of sent notifications to distinct integrations such as PagerDuty, Slack and so on. On negative axis are displayed failed notifications.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_notifications_total{pod=~\"$instance\"}[$__rate_interval])) by (integration)",
       "legendFormat": "{{ integration}}"
      },
      {
       "expr": "sum(increase(alertmanager_notifications_failed_total{pod=~\"$instance\"}[$__rate_interval])) by (integration)",
       "legendFormat": "Failed {{ integration }}"
      }
     ]
    },
    {
     "title": "Notification durations per integration on $instance",
     "type": "timeseries",
     "description": "Duration of notification sends in 0.99 and 0.9 quantiles per integration.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(alertmanager_notification_latency_seconds_bucket{pod=~\"$instance\"}[$__rate_interval])) by (integration)",
       "legendFormat": "0.9q {{ integration }}"
      }
     ]
    },
    {
     "title": "Silences GC duraton on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(alertmanager_silences_gc_duration_seconds_sum{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Silecnces GC  duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active alerts in $instance",
     "type": "timeseries",
     "description": "Number of alerts by state such as `active`, `suppressed` etc.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_alerts{pod=~\"$instance\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Received alerts by status for $instance",
     "type": "timeseries",
     "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_alerts_received_total{pod=~\"$instance\"}[$__rate_interval])) by (status)",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Silences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Silences count by state on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_silences{pod=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Silences query count on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_silences_queries_total{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Silecnces query count"
      },
      {
       "expr": "increase(alertmanager_silences_query_errors_total{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Silecnces query fails"
      }
     ]
    },
    {
     "title": "Silences query duration on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 106 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(alertmanager_silences_query_duration_seconds_bucket{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Silecnces query duration"
      }
     ]
    },
    {
     "title": "Silences snapshot size on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 112 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "alertmanager_silences_snapshot_size_bytes{pod=~\"$instance\"}",
       "legendFormat": "Silecnces snapshot size"
      }
     ]
    },
    {
     "title": "Silences snapshot duration on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 118 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(alertmanager_silences_snapshot_duration_seconds_sum{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Silecnces snapshot duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clusterhealth score for $instance",
     "type": "timeseries",
     "description": "Shows cluster score representing cluster health. From Hashicorps official documentation: \n> This metric describes a node's perception of its own health based on how well it is meeting the soft real-time requirements of the protocol. This metric ranges from 0 to 8, where 0 indicates \"totally healthy\".\n\nFor more info see https://www.consul.io/docs/agent/telemetry.html#cluster-health",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 137 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_health_score{pod=~\"$instance\"}",
       "legendFormat": "Cluster health score"
      }
     ]
    },
    {
     "title": "Cluster members count on $instance",
     "type": "timeseries",
     "description": "Shows gossip cluster members count in time and failing peers in case of any in red color.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 142 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_members{pod=~\"$instance\"}",
       "legendFormat": "Number of cluster members"
      }
     ]
    },
    {
     "title": "Cluster peers left/joined on $instance",
     "type": "timeseries",
     "description": "On positive axis shows number of peers that joined the cluster and on negative axis number of peers that left the cluster.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 147 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_cluster_peers_left_total{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Cluster joined peers"
      },
      {
       "expr": "increase(alertmanager_cluster_peers_joined_total{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Cluster left peers"
      }
     ]
    },
    {
     "title": "Cluster reconnections on $instance",
     "type": "timeseries",
     "description": "On positive axis is number of attempts to reconnect the cluster. On negative axis if number of failed attempts.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 152 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_cluster_reconnections_total{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Sucessful reconnections"
      }
     ]
    },
    {
     "title": "Cluster messages count on $instance",
     "type": "timeseries",
     "description": "On positive axis is number of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 157 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_total{pod=~\"$instance\"}[$__rate_interval])) by (msg_type)",
       "legendFormat": "sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_total{pod=~\"$instance\"}[$__rate_interval])) by (msg_type)",
       "legendFormat": "received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages size on $instance",
     "type": "timeseries",
     "description": "On positive axis is size of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 162 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_size_total{pod=~\"$instance\"}[$__rate_interval])) by (msg_type)",
       "legendFormat": "sent {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages queue on $instance",
     "type": "timeseries",
     "description": "On positive axis is number of queued cluster messages and on negative axis number of pruned messages.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 167 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_messages_pruned_total{pod=~\"$instance\"}",
       "legendFormat": "Pruned messaged"
      },
      {
       "expr": "alertmanager_cluster_messages_queued{pod=~\"$instance\"}",
       "legendFormat": "Queued messages"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of oversized gossip messages on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 173 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(alertmanager_oversized_gossip_message_sent_total{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "increase(alertmanager_oversized_gossip_message_failure_total{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "failed {{key}}"
      }
     ]
    },
    {
     "title": "Duration of oversized gossip messages on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 179 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(alertmanager_oversize_gossip_message_duration_seconds_bucket{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Number of  propagated gossip messages on $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 185 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_silences_gossip_messages_propagated_total{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "silences"
      }
     ]
    }
   ]
  },
  {
   "title": "Nflog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nf log queries count for $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 192 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_nflog_queries_total{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Nf log query count"
      },
      {
       "expr": "increase(alertmanager_nflog_query_errors_total{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Nf log query errors"
      }
     ]
    },
    {
     "title": "Nf log query duration for $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 198 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(alertmanager_nflog_query_duration_seconds_bucket{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Nf log query duration"
      }
     ]
    },
    {
     "title": "Nf log snapshot size for $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 204 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "alertmanager_nflog_snapshot_size_bytes{pod=~\"$instance\"}",
       "legendFormat": "Nf log snapshot size"
      }
     ]
    },
    {
     "title": "Nf log snapshot duration for $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 210 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(alertmanager_nflog_snapshot_duration_seconds_sum{pod=~\"$instance\"}[$__rate_interval]) / rate(alertmanager_nflog_snapshot_duration_seconds_sum{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Nf log snapshot size"
      }
     ]
    },
    {
     "title": "Nf log Go GC time for $instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 216 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(alertmanager_nflog_gc_duration_seconds_sum{pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Cluster joined peers"
      }
     ]
    }
   ]
  }
 ]
}