{
 "title": "Homelab / System / UPS",
 "tags": [
  "Homelab",
  "System",
  "UPS",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ups",
    "label": "UPS",
    "query": {
     "query": "label_values(network_ups_tools_device_info,ups)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$ups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ups" },
  {
   "title": "UPS Status",
   "type": "stat",
   "description": " * OL - On line (mains is present)\n * OB - On battery (mains is not present)\n * LB - Low battery\n * HB - High battery\n * RB - The battery needs to be replaced\n * CHRG - The battery is charging\n * DISCHRG - The battery is discharging (inverter is providing load power)\n * BYPASS - UPS bypass circuit is active -- no battery protection is available\n * CAL - UPS is currently performing runtime calibration (on battery)\n * OFF - UPS is offline and is not supplying power to the load\n * OVER - UPS is overloaded\n * TRIM - UPS is trimming incoming voltage (called \"buck\" in some hardware)\n * BOOST - UPS is boosting incoming voltage\n * FSD and SD - Forced Shutdown",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{ups=\"$ups\"} == 1",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Manufacturer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{ups=\"$ups\"}",
     "legendFormat": "{{device_mfr}}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{ups=\"$ups\"}",
     "legendFormat": "{{device_model}}"
    }
   ]
  },
  {
   "title": "Driver",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{ups=\"$ups\"}",
     "legendFormat": "{{driver_name}}/{{driver_version}}/{{driver_version_data}}"
    }
   ]
  },
  {
   "title": "Battery Run Time Left",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Line Volts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{ups=\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}