{{- $files := .Files.Glob "files/dashboards/*.json" }}
{{- range $path, $fileContents := $files }}
{{- $dashboardName := regexReplaceAll "[^A-Za-z0-9-]+" (regexReplaceAll "(^.*/)(.*)\\.json$" $path "${2}") "" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
  name: graphana-dashboard-{{ $dashboardName }}
data:
  {{ $dashboardName }}.json: {{ $.Files.Get $path | toJson }}
{{- end }}