---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ template "grafana.jobSetupGrafana" . }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 5
  template:
    spec:
      containers:
      - name: setup-grafana
        image: curlimages/curl:latest
        command: ["/bin/sh", "/scripts/setup-grafana.sh"]
        env:
        - name: HOMEPAGE_DASHBOARD_UID
          value: "{{ (.Files.Get "files/dashboards/homepage.json" | fromJson).uid }}"
        - name: REQ_URL
          value: "http://{{ .Values.release_name }}-kube-prometheus-stack-grafana"
        - name: "REQ_USERNAME"
          valueFrom:
            secretKeyRef:
              name: grafana-admin-credentials
              key: user
        - name: "REQ_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: grafana-admin-credentials
              key: password
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: script-volume
        configMap:
          name: {{ template "grafana.configMapJobSetupGrafana" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "grafana.configMapJobSetupGrafana" . }}
data:
  setup-grafana.sh: |
{{ .Files.Get "files/scripts/setup-grafana.sh" | indent 4 }}